config/routes.rb
Rails.application.routes.draw do
  get 'home/index'

  resources :funcionarios
  resources :departamentos
  resources :empresas

end

app/models/departamento.rb
class Departamento < ActiveRecord::Base
  belongs_to :empresa
end

app/models/empresa.rb
class Empresa < ActiveRecord::Base
end

app/models/funcionario.rb
class Funcionario < ActiveRecord::Base
  belongs_to :departamento
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/departamentos_controller.rb
class DepartamentosController < ApplicationController
  before_action :set_departamento, only: [:show, :edit, :update, :destroy]

  # GET /departamentos
  # GET /departamentos.json
  def index
    @departamentos = Departamento.all
  end

  # GET /departamentos/1
  # GET /departamentos/1.json
  def show
  end

  # GET /departamentos/new
  def new
    @departamento = Departamento.new
  end

  # GET /departamentos/1/edit
  def edit
  end

  # POST /departamentos
  # POST /departamentos.json
  def create
    @departamento = Departamento.new(departamento_params)

    respond_to do |format|
      if @departamento.save
        format.html { redirect_to @departamento, notice: 'Departamento was successfully created.' }
        format.json { render :show, status: :created, location: @departamento }
      else
        format.html { render :new }
        format.json { render json: @departamento.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /departamentos/1
  # PATCH/PUT /departamentos/1.json
  def update
    respond_to do |format|
      if @departamento.update(departamento_params)
        format.html { redirect_to @departamento, notice: 'Departamento was successfully updated.' }
        format.json { render :show, status: :ok, location: @departamento }
      else
        format.html { render :edit }
        format.json { render json: @departamento.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /departamentos/1
  # DELETE /departamentos/1.json
  def destroy
    @departamento.destroy
    respond_to do |format|
      format.html { redirect_to departamentos_url, notice: 'Departamento was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_departamento
      @departamento = Departamento.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def departamento_params
      params.require(:departamento).permit(:empresa_id, :nome, :ramal, :responsavel)
    end
end

app/controllers/empresas_controller.rb
class EmpresasController < ApplicationController
  before_action :set_empresa, only: [:show, :edit, :update, :destroy]

  # GET /empresas
  # GET /empresas.json
  def index
    @empresas = Empresa.all
  end

  # GET /empresas/1
  # GET /empresas/1.json
  def show
  end

  # GET /empresas/new
  def new
    @empresa = Empresa.new
  end

  # GET /empresas/1/edit
  def edit
  end

  # POST /empresas
  # POST /empresas.json
  def create
    @empresa = Empresa.new(empresa_params)

    respond_to do |format|
      if @empresa.save
        format.html { redirect_to @empresa, notice: 'Empresa was successfully created.' }
        format.json { render :show, status: :created, location: @empresa }
      else
        format.html { render :new }
        format.json { render json: @empresa.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /empresas/1
  # PATCH/PUT /empresas/1.json
  def update
    respond_to do |format|
      if @empresa.update(empresa_params)
        format.html { redirect_to @empresa, notice: 'Empresa was successfully updated.' }
        format.json { render :show, status: :ok, location: @empresa }
      else
        format.html { render :edit }
        format.json { render json: @empresa.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /empresas/1
  # DELETE /empresas/1.json
  def destroy
    @empresa.destroy
    respond_to do |format|
      format.html { redirect_to empresas_url, notice: 'Empresa was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_empresa
      @empresa = Empresa.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def empresa_params
      params.require(:empresa).permit(:nome, :endereco, :telefone)
    end
end

app/controllers/funcionarios_controller.rb
class FuncionariosController < ApplicationController
  before_action :set_funcionario, only: [:show, :edit, :update, :destroy]

  # GET /funcionarios
  # GET /funcionarios.json
  def index
    @funcionarios = Funcionario.all
  end

  # GET /funcionarios/1
  # GET /funcionarios/1.json
  def show
  end

  # GET /funcionarios/new
  def new
    @funcionario = Funcionario.new
  end

  # GET /funcionarios/1/edit
  def edit
  end

  # POST /funcionarios
  # POST /funcionarios.json
  def create
    @funcionario = Funcionario.new(funcionario_params)

    respond_to do |format|
      if @funcionario.save
        format.html { redirect_to @funcionario, notice: 'Funcionario was successfully created.' }
        format.json { render :show, status: :created, location: @funcionario }
      else
        format.html { render :new }
        format.json { render json: @funcionario.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /funcionarios/1
  # PATCH/PUT /funcionarios/1.json
  def update
    respond_to do |format|
      if @funcionario.update(funcionario_params)
        format.html { redirect_to @funcionario, notice: 'Funcionario was successfully updated.' }
        format.json { render :show, status: :ok, location: @funcionario }
      else
        format.html { render :edit }
        format.json { render json: @funcionario.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /funcionarios/1
  # DELETE /funcionarios/1.json
  def destroy
    @funcionario.destroy
    respond_to do |format|
      format.html { redirect_to funcionarios_url, notice: 'Funcionario was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_funcionario
      @funcionario = Funcionario.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def funcionario_params
      params.require(:funcionario).permit(:departamento_id, :nome, :cargo, :sexo, :endereco)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/departamentos_helper.rb
module DepartamentosHelper
end

app/helpers/empresas_helper.rb
module EmpresasHelper
end

app/helpers/funcionarios_helper.rb
module FuncionariosHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/departamentos/_form.html.erb
<%= simple_form_for(@departamento) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.association :empresa, label_method: :nome %>
    <%= f.input :nome %>
    <%= f.input :ramal %>
    <%= f.input :responsavel %>
  </div>

  <div class="form-actions">
    <%= f.submit 'Salvar' %>
  </div>
<% end %>

app/views/departamentos/edit.html.erb
<h1>Editing Departamento</h1>

<%= render 'form' %>

<%= link_to 'Show', @departamento %> |
<%= link_to 'Back', departamentos_path %>

app/views/departamentos/index.html.erb
<body style="background-color:black">
<p id="notice"><%= notice %></p>

<h1>Aqui você irá cadastrar os seus Departamentos</h1>
<br />
<br />
<br />
<br />

<table>
  <thead>
    <tr>
      <th>Empresa--------</th>
      <th>Nome--------</th>
      <th>Ramal--------</th>
      <th>Responsavel--------</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @departamentos.each do |departamento| %>
      <tr>
        <td><%= departamento.empresa %></td>
        <td><%= departamento.nome %></td>
        <td><%= departamento.ramal %></td>
        <td><%= departamento.responsavel %></td>
        <td><%= link_to 'Show', departamento %></td>
        <td><%= link_to 'Edit', edit_departamento_path(departamento) %></td>
        <td><%= button_to 'Excluir', departamento, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />

<%= link_to 'New Departamento', new_departamento_path %>

app/views/departamentos/new.html.erb
<h1>New Departamento</h1>

<%= render 'form' %>

<%= link_to 'Back', departamentos_path %>

app/views/departamentos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Empresa:</strong>
  <%= @departamento.empresa.nome if @departamento.empresa %>
</p>

<p>
  <strong>Nome:</strong>
  <%= @departamento.nome %>
</p>

<p>
  <strong>Ramal:</strong>
  <%= @departamento.ramal %>
</p>

<p>
  <strong>Responsavel:</strong>
  <%= @departamento.responsavel %>
</p>

<%= link_to 'Edit', edit_departamento_path(@departamento) %> |
<%= link_to 'Back', departamentos_path %>

app/views/empresas/_form.html.erb
<%= simple_form_for(@empresa) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :nome %>
    <%= f.input :endereco %>
    <%= f.input :telefone %>
  </div>

  <div class="form-actions">
    <%= f.submit 'Salvar' %>
  </div>
<% end %>

app/views/empresas/edit.html.erb
<h1>Editing Empresa</h1>

<%= render 'form' %>

<%= link_to 'Show', @empresa %> |
<%= link_to 'Back', empresas_path %>

app/views/empresas/index.html.erb
<body style="background-color:black">
<p id="notice"><%= notice %></p>

<h1>Aqui você irá cadastrar as suas Empresas</h1>
<br />
<br />
<br />
<br />

<table>
  <thead>
    <tr>
      <th>Nome--------</th>
      <th>Endereco--------</th>
      <th>Telefone--------</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @empresas.each do |empresa| %>
      <tr>
        <td><%= empresa.nome %></td>
        <td><%= empresa.endereco %></td>
        <td><%= empresa.telefone %></td>
        <td><%= link_to 'Show', empresa %></td>
        <td><%= link_to 'Edit', edit_empresa_path(empresa) %></td>
        <td><%= button_to 'Excluir', empresa, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />

<%= link_to 'New Empresa', new_empresa_path %>

app/views/empresas/new.html.erb
<h1>New Empresa</h1>

<%= render 'form' %>

<%= link_to 'Back', empresas_path %>

app/views/empresas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nome:</strong>
  <%= @empresa.nome %>
</p>

<p>
  <strong>Endereco:</strong>
  <%= @empresa.endereco %>
</p>

<p>
  <strong>Telefone:</strong>
  <%= @empresa.telefone %>
</p>

<%= link_to 'Edit', edit_empresa_path(@empresa) %> |
<%= link_to 'Back', empresas_path %>

app/views/funcionarios/_form.html.erb
<%= simple_form_for(@funcionario) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.association :departamento,  label_method: :nome %>
    <%= f.input :nome %>
    <%= f.input :cargo %>
    <%= f.input :sexo %>
    <%= f.input :endereco %>
  </div>

  <div class="form-actions">
    <%= f.submit 'Salvar' %>
  </div>
<% end %>

app/views/funcionarios/edit.html.erb
<h1>Editing Funcionario</h1>

<%= render 'form' %>

<%= link_to 'Show', @funcionario %> |
<%= link_to 'Back', funcionarios_path %>

app/views/funcionarios/index.html.erb
<body style="background-color:black">
<p id="notice"><%= notice %></p>

<h1> Aqui você irá cadastrar os seus Funcionários</h1>
<br />
<br />
<br />
<br />

<table>
  <thead>
    <tr>
      <th>Departamento--------</th>
      <th>Nome--------</th>
      <th>Cargo--------</th>
      <th>Sexo--------</th>
      <th>Endereco--------</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @funcionarios.each do |funcionario| %>
      <tr>
        <td><%= funcionario.departamento %></td>
        <td><%= funcionario.nome %></td>
        <td><%= funcionario.cargo %></td>
        <td><%= funcionario.sexo %></td>
        <td><%= funcionario.endereco %></td>
        <td><%= link_to 'Show', funcionario %></td>
        <td><%= link_to 'Edit', edit_funcionario_path(funcionario) %></td>
        <td><%= button_to 'Excluir', funcionario, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />

<br>

<%= link_to 'New Funcionario', new_funcionario_path %>

app/views/funcionarios/new.html.erb
<h1>New Funcionario</h1>

<%= render 'form' %>

<%= link_to 'Back', funcionarios_path %>

app/views/funcionarios/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Departamento:</strong>
  <%= @funcionario.departamento.nome if @funcionario.departamento %>
</p>

<p>
  <strong>Nome:</strong>
  <%= @funcionario.nome %>
</p>

<p>
  <strong>Cargo:</strong>
  <%= @funcionario.cargo %>
</p>

<p>
  <strong>Sexo:</strong>
  <%= @funcionario.sexo %>
</p>

<p>
  <strong>Endereco:</strong>
  <%= @funcionario.endereco %>
</p>

<%= link_to 'Edit', edit_funcionario_path(@funcionario) %> |
<%= link_to 'Back', funcionarios_path %>

app/views/home/index.html.erb
<!DOCTYPE html>
<html>
		<head>
			<meta charset="utf-8">
      
		</head>
					<body style="background-color:black">
							
							<h4 style="font-family:Caslon;text-align:center;color:red,font-size:18px">Site de Cadastro de Empresas</h4>
<hr />
          
<hr />
           
							
									
	<h3>Sejam bem-vindos,</h3>
 <h3>Nosso site tem o objetivo de cadastrar várias empresas e seus respectivos departamentos e funcionários.</h3>
									
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
									
             
						
       
					<li> Cadastre você também...</li>



<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />











					<li> Site criado por Diogo William Bastos </li>
        
    				
                        
 <hr/>

          </body>
    </head>
</head>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>

<title>Empresas e Empresas</title>
<%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
<%= csrf_meta_tags %>

<link rel="stylesheet" href="css/reset.css" type="text/css" media="screen">
<link rel="stylesheet" href="css/style.css" type="text/css" media="screen">
<link rel="stylesheet" href="css/layout.css" type="text/css" media="screen">
<script type="text/javascript" src="js/jquery-1.6.min.js"></script>
<script src="js/cufon-yui.js" type="text/javascript"></script>
<script src="js/cufon-replace.js" type="text/javascript"></script>
<script src="js/Open_Sans_400.font.js" type="text/javascript"></script>
<script src="js/Open_Sans_Light_300.font.js" type="text/javascript"></script> 
<script src="js/Open_Sans_Semibold_600.font.js" type="text/javascript"></script>  
<script type="text/javascript" src="js/tms-0.3.js"></script>
<script type="text/javascript" src="js/tms_presets.js"></script> 
<script type="text/javascript" src="js/jquery.easing.1.3.js"></script> 
<script src="js/FF-cash.js" type="text/javascript"></script>
</head>
<body = id="page1">



<div class="row-2">
					<nav>
						<ul class="menu">
						  <li><%= link_to 'Home', home_index_path %></li>
						  <li><%= link_to 'Cadastro Empresas', empresas_path %></li>
						  <li><%= link_to 'Cadastro Departamentos', departamentos_path %></li>
						  <li><%= link_to 'Cadastro Funcionários', funcionarios_path %></li>
						</ul>
					</nav>
				</div>

<%= yield %>

</body>
</html>